
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int UPLUS = 12;
  public static final int POW = 6;
  public static final int UMINUS = 11;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int RIGHT_BRACKET = 9;
  public static final int DIV = 5;
  public static final int REAL = 13;
  public static final int error = 1;
  public static final int SEMICOLON = 10;
  public static final int LEFT_BRACKET = 8;
  public static final int TIMES = 4;
  public static final int SQRTP = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "SQRTP",
  "LEFT_BRACKET",
  "RIGHT_BRACKET",
  "SEMICOLON",
  "UMINUS",
  "UPLUS",
  "REAL"
  };
}

